<?xml version="1.0"?>
<package format="2">
  <name>static_avoid</name>
  <version>0.0.1</version>
  <description>Reference-path-aware static obstacle avoidance for Bunker Mini.</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rospy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>livox_ros_driver2</exec_depend>
</package>
